- name: Install additional dependencies  
  apt:
    name: 
      - python-nibabel
      - python-numpy
      - python-scipy
    state: latest

- name: Unpack gradunwarp
  unarchive:
    src: https://github.com/Washington-University/gradunwarp/archive/v1.1.0.tar.gz
    dest: /opt
    remote_src: yes

- name: Run gradunwarp installer
  command: python setup.py install
  args:
    chdir: /opt/gradunwarp-1.1.0

- name: Test run gradunwarp (this task should fail, then be ignored)
  command: gradient_unwarp.py
  ignore_errors: yes
  register: gradunwarp_output

- name: Assert that gradunwarp is properly installed
  assert:
    that:
      - "'infile outfile' in gradunwarp_output.stderr"
