- name: Install Connectome Workbench
  apt:
    name: 
      - connectome-workbench
    state: latest

- name: Strip .no.ABI-tag from shared libraries
  shell: strip --remove-section=.note.ABI-tag /usr/lib/x86_64-linux-gnu/libQt5*.so.5
  args:
    executable: /usr/bin/bash

- name: Test run Connectome Workbench
  command: wb_command
  register: connectome_workbench_output

- name: Assert that Connectome Workbench is properly installed
  assert:
    that:
      - "'Version: 1.3.2' in connectome_workbench_output.stdout"
